### ISSUE TITLE
ConsultorioMedico

### ISSUE THREAD

**Issue by Kevin11111111** [reymundotenorio/ConsultorioMedico#1]
Buenas días, caballero una pregunta, cual es el Usuario y la Contraseña del proyecto de Consultorio Medico?, es que quisiera saber para acomodar el proyecto un poquito para un trabajo de la Universidad

Saludos

Espero una pronta respuesta

**Comment by reymundotenorio** [comment]
Hola, por razones de seguridad, existe un archivo donde se encuentran las variables con el usuario y contrasena del usuario "root" de MySQL, este archivo fue ignorado por Git y por eso no esta disponible en el repositorio, te recomiendo que crees este archivo en la carpeta Credenciales con el nombre de clase "UserPass.java"o reemplaza con los valores del usuario y contrasena de tu usuario "root" en el archivo "InicioSesion.java" en la linea 174, esta clase la encuentras en src/Ventanas/InicioSesion.java

Cuando logres establecer la conexion con la base de datos y habiendo ejecutado el Query, inicia sesion con el usuario "Admin" y contrasena "1234". Estos datos se auto insertan al ejecutar el Query, puedes ver esta informacion en las lineas 86 y 87 del archivo "Clinica Query.sql" ubicado en la raiz del proyecto.

Cualquier pregunta, hazmela saber.

**Comment by Kevin11111111** [comment]
Gracias por la información y por responde a mi mensaje, pero mira que lo he intentado tal cual como me lo dijiste pero no me deja pasar de la contraseña, siempre me aparece que error de usuario y contraseña

**Comment by LeoCaizaMurillo** [comment]
Hola ingeniero soy estudiante universitario porfavor ayudeme con el sistema del consultorio
no puedo lograr conectarme a la base de datos en mysql
yo uso sql server por eso se me complica un poco
