### ISSUE TITLE
ayuda

### ISSUE THREAD

**Issue by LeoCaizaMurillo** [reymundotenorio/ConsultorioMedico#2]
Hola ingeniero soy estudiante universitario porfavor ayudeme con el sistema del consultorio
no puedo lograr conectarme a la base de datos en mysql
yo uso sql server por eso se me complica un poco

**Comment by reymundotenorio** [comment]
Hola, podría proporcionarme un poco mas de información sobre el problema que esta presentando??  Ya tiene instalado MySQL Server? Ha creado ya la Base de Datos con el Query que esta dentro del proyecto?

**Comment by LeoCaizaMurillo** [comment]
si ingeniero ya tengo creada la base de datos con el query que nos proporciono en github pero no puedo establecer la conexion entre la base de datos creada y el programa en netbeans 
no puedo autenticar en el login

**Comment by reymundotenorio** [comment]
En la siguiente ruta del proyecto: _ConsultorioMedico/src/Credenciales/UserPass.java_ tienes que agregar, a la variable **Pass**, la contrasena del usuario "root" de MySQL. Has realizado este paso @LeoCaizaMurillo ?

` public static String Pass = "CONTRASENA_DEL_USUARIO_ROOT_MYSQL";`

![consultorioclinicocredenciales](https://user-images.githubusercontent.com/14797730/47378425-4cc1e400-d6b5-11e8-87e2-1e80dec3b33b.PNG)

**Comment by LeoCaizaMurillo** [comment]
si ya lo hice y lo tengo asi

package Credenciales;

/**
 *
 * @author Reymundo Tenorio Q
 */
public class UserPass { 
    
    public static String User = "root";
    public static String Pass = "0927697409"; // esta es la clave de mi mysql con esa entre y cree la base en el workbench
    
}

**Comment by reymundotenorio** [comment]
Si, asi tenia que ser la configuracion. Ahora, podrias especificarme que error presentas al momento de ejecutar el sistema? Seria excelente si enviaras un screenshot del error @LeoCaizaMurillo

**Comment by LeoCaizaMurillo** [comment]
![error clinica mysql](https://user-images.githubusercontent.com/40079332/47475116-c524c400-d7df-11e8-9620-093229d6440c.jpg)



ese error me da y puse el user y el pass que estan en la clase

**Comment by reymundotenorio** [comment]
Prueba con el **_Usuario_** = **Admin** y la **_Contraseña_** = **1234**; en el archivo _Clinica Query.sql_ en las líneas 86/87 puedes observar que se inserta el usuario "**Admin**" con la contraseña "**1234**" y con rol "**Admin**" @LeoCaizaMurillo

**Comment by LeoCaizaMurillo** [comment]
lo acabo de hacer ingeniero me sigue mandando error

**Comment by reymundotenorio** [comment]
Hola @LeoCaizaMurillo he resuelto el problema actualizando la libreria de MySQL Connector. Prueba descargando la nueva version del proyecto.

**Comment by LeoCaizaMurillo** [comment]
buenos días @reymundotenorio  
Ya la voy a probar Gracias Ingeniero

**Comment by reymundotenorio** [comment]
Hola @LeoCaizaMurillo, solamente clona nuevamente el proyecto ejecutando **git clone https://github.com/reymundotenorio/ConsultorioMedico** o actualiza tu repositorio actual con **git pull origin master**

**Comment by reymundotenorio** [comment]
Hola @LeoCaizaMurillo, ya te funciono correctamente la aplicacion?

**Comment by LeoCaizaMurillo** [comment]
![error 2 mysql](https://user-images.githubusercontent.com/40079332/48450071-c9a32380-e772-11e8-9f1c-e39abd3cb6e0.jpg)

buenas noches ingeniero @reymundotenorio estuve tratado de arreglar el problema primero con la version de driver y despues de la zona horaria al final me sigue saliendo este error le adjunto una  foto para que vea en consola

**Comment by LeoCaizaMurillo** [comment]
disculpe la demora en responder estaba sin internet y tambien examenes en la u

**Comment by javatlacati** [comment]
En el código se está tratando de obtener el driver de mysql mediante JDBC `com.mysql.jdbc.Driver`, para SQLServer el driver es distinto, es por ello que no se puede conectar.

**Comment by Zamphiropolos** [comment]
> ![error clinica mysql](https://user-images.githubusercontent.com/40079332/47475116-c524c400-d7df-11e8-9620-093229d6440c.jpg)
> 
> ese error me da y puse el user y el pass que estan en la clase

utiliza mysql 8.xx soluciona el problema
